### ISSUE TITLE
Feature Request:  auto-updater

### ISSUE THREAD

**Issue by Babscoole** [cmkushnir/NMSModBuilder#1]
Something for the future.  App will detect and possibly install new version when released.  Thanks.

**Comment by cmkushnir** [comment]
I agree that would be nice, but writing auto-updaters can be a pain.  In this case there is also the issue of having scripts in the download that could overwrite changes to the same scripts the user has made.  I'd rather leave it to the user to overwrite their files instead of blaming an installer. :)

Instead I could add current and available app versions in the status bar and highlight the current red if there is a newer available.  Clicking on the newer in the status bar would open a download dialog.

The user would then be responsible for backing up their scripts before unzipping the new version over the old.

**Comment by Babscoole** [comment]
Perfect compromise sir.  :)

**Comment by cmkushnir** [comment]
The next release will have the following:
![Untitled](https://user-images.githubusercontent.com/81258013/119733354-674d3280-be47-11eb-89aa-130497558028.png)

I don't auto-check as there is network overhead in downloading the release info from GitHub; I want the user to know a network connection is happening e.g. in-case it hangs or something.

If there is no newer version you get:
![Untitled2](https://user-images.githubusercontent.com/81258013/119733624-cca12380-be47-11eb-8ed8-a66e90b12e8f.png)

If there is a newer version you get:
![Untitled3](https://user-images.githubusercontent.com/81258013/119733803-06722a00-be48-11eb-8ad3-b4839e6c1c8d.png)
You can click the button to the right of the target to pick a new location to save to.
