### ISSUE TITLE
[Feature Request] Close to system tray option

### ISSUE THREAD

**Issue by DeathWrench** [cmkushnir/NMSModBuilder#2]
I keep accidentally closing it and then 10 seconds later opening it back up because I didn't actually mean to.  This is probably a "me" problem but still think it'd be nice to have.

**Comment by cmkushnir** [comment]
I generally only use 'close to tray' functionality for service type apps, apps that need to do something in the background.  For normal apps like this i suggest just minimize instead of close the app.  I will keep this suggestion in mind, but it's at the bottom of the todo list.
There are also times when you must restart the app.  For example, the app should not be open when the game is being updated, as the app caches the game pak meta-data and doesn't watch those files for change, so I don't keep the app open when steam is open|running.

**Comment by DeathWrench** [comment]
No worries, had no idea about why it shouldn't be left on though so that will be good to know. I have a somewhat hacky workaround for now. Using autohotkey. [This post is where I found the script.](https://www.autohotkey.com/boards/viewtopic.php?p=419426&sid=857d38dfb1fceb49e2435b99653ba1fe#p419426)
``#If OnMyCloseButton()``
``LButton:: WinMinimize``
``#If``
``OnMyCloseButton() {``
``   Static MyWindowCriteria := "NMS : Mod Builder" ; change to meet your neeeds``
``   Critical``
``   SetTitleMatchMode, 2``
``   CoordMode, Mouse, Screen``
``   MouseGetPos, X, Y, MID``
``   If (WID := WinExist(MyWindowCriteria)) && (WID = MID) {``
``      SendMessage, 0x0084, 0, (X & 0xFFFF) | ((Y & 0xFFFF) << 16) ; WM_NCHITTEST``
``      Return (ErrorLevel = 20) ; HTCLOSE``
``   }``
``   Return False``
``}``

Pretty useful, instead of closing the window by pressing the X button, it minimizes it.
