### ISSUE TITLE
GcRefinerRecipe does not contain a definition for 'Name'

### ISSUE THREAD

**Issue by ruslan79k** [cmkushnir/NMSModBuilder#3]
Trying to run...

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1061	'GcRefinerRecipe' does not contain a definition for 'Name' and no accessible extension method 'Name' accepting a first argument of type 'GcRefinerRecipe' could be found (are you missing a using directive or an assembly reference?)	cmkNMSCommon	D:\Programming\C#\Projects\NMSModBuilder-main\NMSModBuilder-main\Common\NMS\Game\Game.Recipes.cs	120	Active

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0117	'GcRefinerRecipe' does not contain a definition for 'Name'	cmkNMSCommon	D:\Programming\C#\Projects\NMSModBuilder-main\NMSModBuilder-main\Common\NMS\MBINC\Recipe.cs	74	Active

![error1](https://user-images.githubusercontent.com/7738705/166954361-1d8f72e6-0fa3-4e68-a128-32ab2c67bb7c.JPG)
![error2](https://user-images.githubusercontent.com/7738705/166954380-81444fff-b1e8-40d5-b634-5e9a5706b92b.JPG)

**Comment by cmkushnir** [comment]
You don't mention the important things:
- what version of the app
- what version of the game and what OS and platform (steam, gog, xbox, ...)
- what libMBIN.dll version

The issue is due to an invalid combo of the above.  Like MBINC (MBinCompiler|libMBIN), the app makes no attempt to stay backwards compatible, it's not feasible w/ the amount of changes that are made to the game.  As such, a given version of the app will only work with certain versions of the game and libMBIN.

NMS 3.81 changed the recipe structure, it made breaking changes to MBINC and the app.  The latest version of the app is always on GitHub, Nexus may lag behind.  In this case the issue is almost certainly that you are using an old version of the app with a newer version of the game.
